# Desafio do Kaggle: Quantidade de sobrevivente no Titanic

## Importando os dados, fazendo análise exploratória, transformando as variáveis em explicativas e alvo.

In [106]:
import pandas as pd

In [107]:
dados = pd.read_csv('gender_submission.csv')
dados

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [108]:
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
dtypes: int64(2)
memory usage: 6.7 KB

In [109]:
teste = pd.read_csv('test.csv')
id_passageiro = teste['PassengerId']
teste

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [110]:
treino = pd.read_csv('train.csv')
treino

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [111]:
mode_embarked = treino['Embarked'].mode()[0]
treino['Embarked'] = treino['Embarked'].fillna(mode_embarked)

In [112]:
treino['Embarked'].unique()

<StringArray>
['S', 'C', 'Q']
Length: 3, dtype: str

In [113]:
cabine = treino['Cabin']
treino = treino.drop('Cabin', axis= 1)
ticket = treino['Ticket']
treino = treino.drop('Ticket', axis= 1)
nome = treino['Name']
treino = treino.drop('Name', axis= 1)
x = treino.drop('Survived', axis= 1)
y = treino['Survived']

In [114]:
teste = teste.drop('Cabin', axis= 1)
teste = teste.drop('Ticket', axis= 1)
teste = teste.drop('Name', axis= 1)

In [115]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder

In [116]:
colunas_teste = teste.columns
colunas = x.columns
colunas_teste

Index(['PassengerId', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='str')

In [117]:
treino.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    str
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Fare         891 non-null    float64
 8   Embarked     891 non-null    str
dtypes: float64(2), int64(5), str(2)
memory usage: 62.8 KB

In [118]:
one_hot = make_column_transformer((
    OneHotEncoder(),
    ['Sex', 'Embarked', 'Pclass']
),
    remainder= 'passthrough',
    sparse_threshold= 0)

In [119]:
teste = one_hot.fit_transform(teste)

In [120]:
teste.shape

(418, 13)

In [121]:
x = one_hot.fit_transform(x)

In [122]:
one_hot.get_feature_names_out(colunas)

array(['onehotencoder__Sex_female', 'onehotencoder__Sex_male',
       'onehotencoder__Embarked_C', 'onehotencoder__Embarked_Q',
       'onehotencoder__Embarked_S', 'onehotencoder__Pclass_1',
       'onehotencoder__Pclass_2', 'onehotencoder__Pclass_3',
       'remainder__PassengerId', 'remainder__Age', 'remainder__SibSp',
       'remainder__Parch', 'remainder__Fare'], dtype=object)

In [123]:
one_hot.get_feature_names_out(colunas_teste)

array(['onehotencoder__Sex_female', 'onehotencoder__Sex_male',
       'onehotencoder__Embarked_C', 'onehotencoder__Embarked_Q',
       'onehotencoder__Embarked_S', 'onehotencoder__Pclass_1',
       'onehotencoder__Pclass_2', 'onehotencoder__Pclass_3',
       'remainder__PassengerId', 'remainder__Age', 'remainder__SibSp',
       'remainder__Parch', 'remainder__Fare'], dtype=object)

In [124]:
dt_x = pd.DataFrame(x, columns= one_hot.get_feature_names_out(colunas))

In [125]:
dt_x

,onehotencoder__Sex_female,onehotencoder__Sex_male,onehotencoder__Embarked_C,onehotencoder__Embarked_Q,onehotencoder__Embarked_S,onehotencoder__Pclass_1,onehotencoder__Pclass_2,onehotencoder__Pclass_3,remainder__PassengerId,remainder__Age,remainder__SibSp,remainder__Parch,remainder__Fare
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,22.0,1.0,0.0,7.2500
1,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0,38.0,1.0,0.0,71.2833
2,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,3.0,26.0,0.0,0.0,7.9250
3,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,4.0,35.0,1.0,0.0,53.1000
4,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,5.0,35.0,0.0,0.0,8.0500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,887.0,27.0,0.0,0.0,13.0000
887,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,888.0,19.0,0.0,0.0,30.0000
888,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,889.0,NaN,1.0,2.0,23.4500
889,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,890.0,26.0,0.0,0.0,30.0000
890,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,891.0,32.0,0.0,0.0,7.7500

In [126]:
from sklearn.preprocessing import LabelEncoder

In [127]:
label_encoder = LabelEncoder()

In [128]:
y = label_encoder.fit_transform(y)

## Ajustando o modelo Decision Tree

In [129]:
from sklearn.tree import DecisionTreeClassifier

In [130]:
arvore = DecisionTreeClassifier(max_depth= 3)
arvore.fit(x, y)

DecisionTreeClassifier(max_depth=3)

In [131]:
arvore.score(x, y)

0.8271604938271605

In [132]:
arvore.score(teste, dados['Survived'])

0.9665071770334929

In [133]:
previsao = arvore.predict(teste)

In [134]:
prev = pd.DataFrame(previsao, columns= ['Survived'])

In [135]:
res = pd.concat([id_passageiro, prev], axis= 1)

In [136]:
res

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [137]:
res.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
dtypes: int64(2)
memory usage: 6.7 KB

In [138]:
res.to_csv('sobreviventes.csv', index=False)